# Generated by Django 2.2 on 2020-05-11 14:25

import catalog.mixins
import catalog.utils
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, help_text='Необязательно для заполнения руками', max_length=250, verbose_name='Наименование для создания ссылки')),
                ('image', models.ImageField(blank=True, upload_to=catalog.utils.get_random_filename)),
                ('svg_file', models.TextField(blank=True, verbose_name='Текст с тегом svg')),
                ('display_name', models.CharField(blank=True, max_length=250, verbose_name='Название категории вместо изображения')),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('general_category', models.BooleanField(default=False, verbose_name='Общая категория')),
            ],
            options={
                'verbose_name': 'Категория брошюры',
                'verbose_name_plural': 'Категории брошюры',
            },
            bases=(catalog.mixins.SaveModelSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Наименование для создания ссылки')),
                ('brochure_file', models.FileField(blank=True, null=True, upload_to='', validators=[catalog.utils.file_size_and_extension], verbose_name='Брошюра')),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('brochure_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochures', to='brochure.BrochureCategory')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='brochure.Brochure')),
            ],
            options={
                'verbose_name': 'Брошюра',
                'verbose_name_plural': 'Брошюра',
            },
            bases=(catalog.mixins.SaveModelSlugMixin, models.Model),
        ),
    ]
