# Generated by Django 2.2 on 2020-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200511_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-priority'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='func_description',
            field=models.TextField(verbose_name='Функции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='general_description',
            field=models.TextField(verbose_name='Общее описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tech_description',
            field=models.TextField(verbose_name='Характеристики'),
        ),
    ]
