# Generated by Django 2.2 on 2020-05-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200512_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['priority'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
    ]
