# Generated by Django 2.2 on 2020-05-12 12:24

import catalog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200512_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.get_random_filename, verbose_name='Картинка категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='svg_image',
            field=models.TextField(blank=True, null=True, verbose_name='Картинка в формате SVG с тегом svg'),
        ),
    ]
