# Generated by Django 2.2 on 2020-05-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200512_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия продукта', 'verbose_name_plural': 'Серии продукта'},
        ),
    ]
