# Generated by Django 2.2 on 2020-05-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200513_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='В этом поле можно использовать автозаполнение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.Product', verbose_name='Товар к которому привязана картинка'),
        ),
    ]
