# Generated by Django 2.2 on 2020-05-28 19:04

import catalog.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200514_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechDoc',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instruction', models.FileField(blank=True, null=True, upload_to='',
                                                 validators=[catalog.utils.file_size_and_extension],
                                                 verbose_name='Инструкция')),
                ('product', models.ForeignKey(help_text='В этом поле можно использовать автозаполнение',
                                              on_delete=django.db.models.deletion.CASCADE, related_name='instructions',
                                              to='catalog.Product',
                                              verbose_name='Товар к которому привязана инструкция')),
            ],
            options={
                'verbose_name': 'Техническая инструкция к товару',
                'verbose_name_plural': 'Технические инструкции к товару',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='', verbose_name='Краткое описание товара в карточке товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Необязательно для заполнения руками', max_length=350, verbose_name='Наименование для создания ссылки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Не более 250 символов с пробелами', max_length=250, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, verbose_name='Наименование для создания ссылки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Не более 250 символов с пробелами', max_length=250, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.CharField(blank=True, help_text='Необязательно для заполнения руками', max_length=350, null=True, verbose_name='Наименование для формирования URL ссылки'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(help_text='Не более 250 символов с пробелами', max_length=250, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.SlugField(blank=True, help_text='Необязательно для заполнения руками', max_length=350, verbose_name='Наименование для создания ссылки'),
        ),
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(help_text='Не более 250 символов с пробелами', max_length=250, verbose_name='Наименование'),
        ),
    ]
