# Generated by Django 2.2 on 2020-05-30 13:56

import catalog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_migrate_instructions_20200528_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instruction',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[catalog.utils.file_size_and_extension], verbose_name='Инструкция'),
        ),
    ]
