# Generated by Django 2.2 on 2020-05-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_migrate_instructions_20200528_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='simlr',
            field=models.ForeignKey(blank=True, help_text='Укажите в карточке какого товара данный товар будет показан в разделе "Похожие товары"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar', to='catalog.Product', verbose_name='Ссылка на похожий товар'),
        ),
    ]
