# Generated by Django 2.2 on 2020-05-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='instruction',
        ),
    ]
