# Generated by Django 2.2 on 2020-06-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_simlr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание товара в карточке товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='simlr',
            field=models.ForeignKey(blank=True, help_text='Укажите в карточке какого товара данный товар будет показан в разделе "Рекомендованные товары"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar', to='catalog.Product', verbose_name='С каким товаром должен рекомендоваться данный товар'),
        ),
    ]
