# Generated by Django 2.2 on 2020-06-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200603_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Каталог продукта', 'verbose_name_plural': 'Катклоги продуктов'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Тип продукта', 'verbose_name_plural': 'Типы продуктов'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Категория продукта', 'verbose_name_plural': 'Категории продуктов'},
        ),
    ]
