# Generated by Django 2.2 on 2020-07-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200604_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория продукта', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия продукта', 'verbose_name_plural': 'Серии продуктов'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип продукта', 'verbose_name_plural': 'Типы продуктов'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='techdoc',
            name='product',
        ),
        migrations.AddField(
            model_name='techdoc',
            name='product',
            field=models.ManyToManyField(blank=True, help_text='В этом поле можно использовать автозаполнение', related_name='instructions', to='catalog.Product', verbose_name='Товары к которым привязана инструкция'),
        ),
        migrations.CreateModel(
            name='ProductXImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductImage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_links', to='catalog.Product')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ManyToManyField(blank=True, help_text='В этом поле можно использовать автозаполнение', through='catalog.ProductXImage', to='catalog.Product', verbose_name='Товары к которым привязана картинка'),
        ),
    ]
