# Generated by Django 2.2 on 2020-07-26 07:47

from django.db import migrations, models
import django.db.models.deletion


def fill_currency(apps, schema_editor):
    Currency = apps.get_model('catalog', 'Currency')
    Currency(code='RUB', title='Рубль', char_logo='₽').save()
    Currency(code='USD', title='Доллар', char_logo='$').save()
    Currency(code='EUR', title='Евро', char_logo='€').save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200719_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Кодовое название')),
                ('title', models.CharField(help_text='Не более 50 символов с пробелами', max_length=50, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, help_text='Необязательно для заполнения руками', max_length=100, verbose_name='Наименование для создания ссылки')),
                ('svg_logo', models.TextField(blank=True, verbose_name='Изображение в формате svg')),
                ('char_logo', models.CharField(blank=True, max_length=20, verbose_name='Символ валюты вместо изображения')),
            ],
            options={
                'verbose_name': 'Список валют',
                'verbose_name_plural': 'Список валют',
            },
        ),
        migrations.RunPython(fill_currency),
        migrations.AddField(
            model_name='product',
            name='active_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Currency', verbose_name='Отображаемая цена'),
        ),
        migrations.CreateModel(
            name='ProductXCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.Product')),
            ],
            options={
                'unique_together': {('currency', 'product')},
            },
        ),
    ]
