# Generated by Django 2.2 on 2020-05-08 11:17

from django.db import migrations, models
import django.db.models.deletion

from catalog.mixins import SaveModelSlugMixin, SaveModelSlugImageMixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 250 символов', max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, help_text='Необязательно для заполнения руками', max_length=350, verbose_name='Наименование для создания ссылки')),
            ],
            options={
                'verbose_name': 'Тема новости',
                'verbose_name_plural': 'Темы новостей',
            },
            bases=(SaveModelSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 250 символов', max_length=250, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, help_text='Необязательно для заполнения руками', max_length=350, verbose_name='Наименование для создания ссылки')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('image', models.ImageField(upload_to='')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.Topic', verbose_name='Тема новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=(SaveModelSlugImageMixin, models.Model),
        ),
    ]
