# Generated by Django 2.2 on 2020-05-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(help_text='В этом поле можно использовать автозаполнение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.Project', verbose_name='Проект к которому привязана картинка'),
        ),
    ]
