# Generated by Django 2.2 on 2020-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReceivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, verbose_name='Почта')),
                ('is_send_email_notifications', models.BooleanField(default=True, verbose_name='Отправлять сообщения по почте')),
            ],
            options={
                'verbose_name': 'Получатель уведомлений',
                'verbose_name_plural': 'Получатели уведомлений',
            },
        ),
        migrations.CreateModel(
            name='FeedbackHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Телефон')),
                ('comment', models.CharField(blank=True, max_length=999, verbose_name='Комментарий')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История уведомлений',
                'verbose_name_plural': 'Историиуведомлений',
            },
        ),
    ]
