# Generated by Django 2.2 on 2020-05-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackhistory',
            options={'verbose_name': 'История уведомлений', 'verbose_name_plural': 'Истории уведомлений'},
        ),
    ]
