# Generated by Django 2.2 on 2020-05-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200513_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackhistory',
            old_name='datatime',
            new_name='creation_date',
        ),
    ]
