# Generated by Django 2.2 on 2020-05-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200512_1600'),
        ('core', '0002_auto_20200513_1924'),
    ]

    operations = [
    ]
