# Generated by Django 2.2 on 2020-05-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20200513_2032'),
        ('core', '0003_auto_20200514_1232'),
    ]

    operations = [
    ]
